### ISSUE TITLE
staticmethod и classmethod

### ISSUE THREAD

**Issue by taimaskhanov11** [pomponchik/polog#15]
происходит ли логирование статических методов и методов класса?

**Comment by pomponchik** [comment]
В общем случае нет, но есть варианты.

Дело в том, что статические методы и методы класса де-факто работают через протокол дескриптора. Это делает невозможным навешивание любых декораторов поверх таких методов. То есть, если вы попытаетесь проделать что-то подобное, вы получите ошибку:

`
class A:
    @log
    @staticmethod
    def a():
        print('lol')
`

Также в текущей версии Polog (0.0.13) @log для таких методов не будет работать как декоратор класса. Это происходит без дополнительного оповещения или выбрасывания исключений. Это будет исправлено в одной из будущих версий (скорее всего, в 0.0.14).

Однако вы можете навесить декоратор @log до декораторов @staticmethod или @classmethod, вот так:

`
class A:
    @staticmethod
    @log
    def a():
        print('kek')
`

Это будет работать так, как вы ожидаете.
