### ISSUE TITLE
ModuleNotFoundError: No module named 'fcntl' in Windows

### ISSUE THREAD

**Issue by YevgeniyUN2G** [pomponchik/polog#21]
При импорте библиотеки в Windows 

from polog import config, file_writer
config.add_handlers(file_writer())
from polog import log

выходит следующая ошибка:

File "C:\WorkPlace\getTextYa\venv\lib\site-packages\polog\handlers\file\locks\file_lock.py", line 1, in <module>
    import fcntl
ModuleNotFoundError: No module named 'fcntl'

**Comment by pomponchik** [comment]
Добрый день! Спасибо за обратную связь, будет исправлено в новой версии.

**Comment by pomponchik** [comment]
Новая версия (0.0.17) вышла, данная ошибка исправлена. В будущем планирую добавить регулярные проверки кода на windows-машинах для обеспечения полной переносимости функционала.

Обращаю также внимание, что файловые блокировки при ротации файлов по-прежнему не доступны на windows.

Спасибо еще раз за помощь.
